// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDf_346ikVT_U2_wf-9Mz71A71cMUDmIqQ',
    appId: '1:143443140095:web:18da63c6fd5ce1ad895bca',
    messagingSenderId: '143443140095',
    projectId: 'flutter-dating-app-f3f66',
    authDomain: 'flutter-dating-app-f3f66.firebaseapp.com',
    storageBucket: 'flutter-dating-app-f3f66.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAS_aKrMyJ1zFYQCyEE7geB4QxpqN2rijI',
    appId: '1:143443140095:android:1dc3303229075283895bca',
    messagingSenderId: '143443140095',
    projectId: 'flutter-dating-app-f3f66',
    storageBucket: 'flutter-dating-app-f3f66.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpuzGkg8hgtc5c6yri6LT76jM4MemN1zQ',
    appId: '1:143443140095:ios:a971b2f1a94f5af5895bca',
    messagingSenderId: '143443140095',
    projectId: 'flutter-dating-app-f3f66',
    storageBucket: 'flutter-dating-app-f3f66.appspot.com',
    iosBundleId: 'com.example.flutterDatingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpuzGkg8hgtc5c6yri6LT76jM4MemN1zQ',
    appId: '1:143443140095:ios:04bc67fa48ed660d895bca',
    messagingSenderId: '143443140095',
    projectId: 'flutter-dating-app-f3f66',
    storageBucket: 'flutter-dating-app-f3f66.appspot.com',
    iosBundleId: 'com.example.flutterDatingApp.RunnerTests',
  );
}
